/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "UART.h"
#include "Pin_SCL_aliases.h"
#include "Pin_SCL.h"
#include "Pin_SDA_aliases.h"
#include "Pin_SDA.h"
#include "I2C_MPU6050.h"
#include "I2C_MPU6050_PVT.h"
#include "Timer.h"
#include "LCD.h"
#include "PWM.h"
#include "Clock.h"
#include "SmallServo_aliases.h"
#include "SmallServo.h"
#include "LargeServo_aliases.h"
#include "LargeServo.h"
#include "Joystick_X_aliases.h"
#include "Joystick_X.h"
#include "Joystick_Y_aliases.h"
#include "Joystick_Y.h"
#include "AMux.h"
#include "ADC.h"
#include "SW1_aliases.h"
#include "SW1.h"
#include "LED1_aliases.h"
#include "LED1.h"
#include "LED2_aliases.h"
#include "LED2.h"
#include "LED3_aliases.h"
#include "LED3.h"
#include "LED4_aliases.h"
#include "LED4.h"
#include "SW2_aliases.h"
#include "SW2.h"
#include "ISR_Audio.h"
#include "Timer_Audio.h"
#include "Clock_Audio.h"
#include "ISR.h"
#include "VDAC8.h"
#include "Audio_Out_aliases.h"
#include "Audio_Out.h"
#include "UART_IntClock.h"
#include "LCD_LCDPort_aliases.h"
#include "LCD_LCDPort.h"
#include "ADC_AMux.h"
#include "ADC_Ext_CP_Clk.h"
#include "ADC_IRQ.h"
#include "ADC_theACLK.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

